/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("init.gradle.project.kotlin-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
}

application {
    // Define the main class for the application.
    mainClass.set("init.gradle.project.app.AppKt")
}
