/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package init.gradle.project.app

import init.gradle.project.utilities.StringUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    println(StringUtils.join(tokens))
}
